#!/bin/sh
set -x

if ! snapctl is-connected wayland
then
  echo "Wayland interface not connected!"
  exit 1
fi

wait_for()
{
  until
    until
      inotifywait --event create "$(dirname "$1")"&
      inotify_pid=$!
      [ -e "$1" ] || sleep 2 && [ -e "$1" ]
    do
      wait "${inotify_pid}"
    done
    kill "${inotify_pid}"
    [ -O "$1" ]
  do
    sleep 1
  done
}

real_xdg_runtime_dir=$(dirname "${XDG_RUNTIME_DIR}")
real_wayland=${real_xdg_runtime_dir}/${WAYLAND_DISPLAY:-wayland-0}

# On core systems may need to wait for real XDG_RUNTIME_DIR
wait_for "${real_xdg_runtime_dir}"
wait_for "${real_wayland}"

mkdir -p ${XDG_RUNTIME_DIR}
ln -sf "${real_wayland}" "${XDG_RUNTIME_DIR}"
export MIR_SERVER_WAYLAND_HOST=${WAYLAND_DISPLAY:-wayland-0}
unset WAYLAND_DISPLAY
