#!/bin/sh
set -x

if ! snapctl is-connected wayland
then
  echo "Wayland interface not connected!"
  exit 1
fi

real_xdg_runtime_dir=$(dirname "${XDG_RUNTIME_DIR}")
real_wayland=${real_xdg_runtime_dir}/${WAYLAND_DISPLAY:-wayland-0}

# On core systems may need to wait for real XDG_RUNTIME_DIR
until [ -O "${real_xdg_runtime_dir}" ]
do
  inotifywait --event create "$(dirname "${real_xdg_runtime_dir}")"
done

until [ -O "${real_wayland}" ]
do
  inotifywait --event create $(dirname "${real_wayland}")
done

mkdir -p ${XDG_RUNTIME_DIR}
ln -sf "${real_wayland}" "${XDG_RUNTIME_DIR}"
export MIR_SERVER_WAYLAND_HOST=${WAYLAND_DISPLAY:-wayland-0}
unset WAYLAND_DISPLAY
