name: mir-kiosk-x11
summary: Boilerplate for using mir_kiosk_x11
description: Boilerplate for using mir_kiosk_x11 (for use as a "stage-snap")
base: core20
confinement: strict
grade: stable
adopt-info: mir-kiosk-x11

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  ppa-setup:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -y ppa:mir-team/release
      sudo apt install --assume-yes libmiral-dev
      snapcraftctl pull

  recipe-version:
    plugin: nil
    source: .
    source-type: git
    override-build: |
      git rev-list --count HEAD > $SNAPCRAFT_PART_INSTALL/recipe-version
    prime:
      - -recipe-version

  mir-kiosk-x11:
    after: [recipe-version, ppa-setup]
    plugin: cmake
    source: src
    build-packages:
      - pkg-config
      - libmiral-dev
      - make
      - g++
    override-build: |
      mir_version=`LANG=C apt-cache policy mir-platform-graphics-wayland | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      recipe_version=`cat $SNAPCRAFT_STAGE/recipe-version`
      snapcraftctl set-version $recipe_version-mir$mir_version
      if echo $mir_version | grep -e '+dev' -e '~rc' -q; then snapcraftctl set-grade devel; else snapcraftctl set-grade stable; fi
      snapcraftctl build
    stage-packages:
      - inotify-tools
      - libmiral4
      - mir-platform-graphics-wayland
      - dmz-cursor-theme
      - fonts-freefont-ttf
      - xwayland
      - libbz2-1.0

  env-setup:
    plugin: dump
    source: env-setup
    override-build: |
      snapcraftctl build
      sed s/\$\{SNAPCRAFT_ARCH_TRIPLET}/${SNAPCRAFT_ARCH_TRIPLET}/g --in-place $SNAPCRAFT_PART_INSTALL/hacks/*
